### ISSUE TITLE
mDNS is supported - should be added to the doc

### ISSUE THREAD

**Issue by TotallyFred** [kovyrin/cubiio2#1]
I do not have write access to your repo. I thought mDNS made it easier than messing with DHCP (for most people anyway). 

## Alternative installation (no DHCP tweaking, no IP address).

Your Cubiio2 has a pretty name. It is called cubiio2-<serial number> where <serial number> is specific to your machine. For example cubiio2-a0d5.

It is the same name as
  - the WiFi SSID you found when turning on the cubiio2 for the first time
  - the name of the cubiio2 in the cubiio2 app

You can connect to your cubiio2 from your browser by referring to
  - http://cubiio2-<SN>.local (for example: http://cubiio2-a0d5.local). The .local is very important.

**Comment by kovyrin** [comment]
Thank you very much for your tip! 🙇 
Added it to the document.

If you have any more tips, you can click "edit" on the readme file in this repo and GitHub will automatically create a Pull Request.
